package com.microservice.poc.model.FedLawfulPresence;

public enum DHSID {

   /* I327DocumentID,I551DocumentID,I571DocumentID,I766DocumentID,CertOfCitDocumentID,NatrOfCertDocumentID,
    MacReadI551DocumentID,TempI551DocumentID,I94DocumentID,I94UnexpForeignPassportDocumentID,UnexpForeignPassportDocumentID,
    I20DocumentID,DS2019DocumentID,OtherCase1DocumentID,OtherCase2DocumentID*/

    I327DOCUMENTID, I551DOCUMENTID, I571DOCUMENTID, I766DOCUMENTID, CERTOFCITDOCUMENTID, NATROFCERTDOCUMENTID,
    MACREADI551DOCUMENTID, TEMPI551DOCUMENTID, I94DOCUMENTID, I94UNEXPFOREIGNPASSPORTDOCUMENTID, UNEXPFOREIGNPASSPORTDOCUMENTID,
    I20DOCUMENTID, DS2019DOCUMENTID, OTHERCASE1DOCUMENTID, OTHERCASE2DOCUMENTID
}
